root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 50
exclude_dir = ["assets", "tmp"]
exclude_regex = ["_test.go"]
include_ext = ["go", "html", "md", "css", "js", "svg"]
kill_delay = "0s"
log = "build-errors.log"

[misc]
clean_on_exit = true
