name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.23.4"

      - name: Run tests
        run: go test -cover ./... internal/emoji internal/inlinesvg internal/projects
